// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace LukeKennedy.LSQL.Net {
  public static partial class DataSource
  {
    static readonly string __ServiceName = "DataSource";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::LukeKennedy.LSQL.Net.Query> __Marshaller_Query = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::LukeKennedy.LSQL.Net.Query.Parser));
    static readonly grpc::Marshaller<global::LukeKennedy.LSQL.Net.Result> __Marshaller_Result = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::LukeKennedy.LSQL.Net.Result.Parser));
    static readonly grpc::Marshaller<global::LukeKennedy.LSQL.Net.StreamResult> __Marshaller_StreamResult = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::LukeKennedy.LSQL.Net.StreamResult.Parser));

    static readonly grpc::Method<global::LukeKennedy.LSQL.Net.Query, global::LukeKennedy.LSQL.Net.Result> __Method_Execute = new grpc::Method<global::LukeKennedy.LSQL.Net.Query, global::LukeKennedy.LSQL.Net.Result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Execute",
        __Marshaller_Query,
        __Marshaller_Result);

    static readonly grpc::Method<global::LukeKennedy.LSQL.Net.Query, global::LukeKennedy.LSQL.Net.StreamResult> __Method_ExecuteBatch = new grpc::Method<global::LukeKennedy.LSQL.Net.Query, global::LukeKennedy.LSQL.Net.StreamResult>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "ExecuteBatch",
        __Marshaller_Query,
        __Marshaller_StreamResult);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::LukeKennedy.LSQL.Net.ServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DataSource</summary>
    [grpc::BindServiceMethod(typeof(DataSource), "BindService")]
    public abstract partial class DataSourceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::LukeKennedy.LSQL.Net.Result> Execute(global::LukeKennedy.LSQL.Net.Query request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task ExecuteBatch(grpc::IAsyncStreamReader<global::LukeKennedy.LSQL.Net.Query> requestStream, grpc::IServerStreamWriter<global::LukeKennedy.LSQL.Net.StreamResult> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DataSource</summary>
    public partial class DataSourceClient : grpc::ClientBase<DataSourceClient>
    {
      /// <summary>Creates a new client for DataSource</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public DataSourceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DataSource that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public DataSourceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected DataSourceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected DataSourceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::LukeKennedy.LSQL.Net.Result Execute(global::LukeKennedy.LSQL.Net.Query request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Execute(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::LukeKennedy.LSQL.Net.Result Execute(global::LukeKennedy.LSQL.Net.Query request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Execute, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::LukeKennedy.LSQL.Net.Result> ExecuteAsync(global::LukeKennedy.LSQL.Net.Query request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExecuteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::LukeKennedy.LSQL.Net.Result> ExecuteAsync(global::LukeKennedy.LSQL.Net.Query request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Execute, null, options, request);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::LukeKennedy.LSQL.Net.Query, global::LukeKennedy.LSQL.Net.StreamResult> ExecuteBatch(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExecuteBatch(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::LukeKennedy.LSQL.Net.Query, global::LukeKennedy.LSQL.Net.StreamResult> ExecuteBatch(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_ExecuteBatch, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override DataSourceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DataSourceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(DataSourceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Execute, serviceImpl.Execute)
          .AddMethod(__Method_ExecuteBatch, serviceImpl.ExecuteBatch).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DataSourceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Execute, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::LukeKennedy.LSQL.Net.Query, global::LukeKennedy.LSQL.Net.Result>(serviceImpl.Execute));
      serviceBinder.AddMethod(__Method_ExecuteBatch, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::LukeKennedy.LSQL.Net.Query, global::LukeKennedy.LSQL.Net.StreamResult>(serviceImpl.ExecuteBatch));
    }

  }
}
#endregion
