// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LukeKennedy.LSQL.Net {

  /// <summary>Holder for reflection information generated from service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1zZXJ2aWNlLnByb3RvGgtxdWVyeS5wcm90bxoMcmVzdWx0LnByb3RvMlcK",
            "CkRhdGFTb3VyY2USHAoHRXhlY3V0ZRIGLlF1ZXJ5GgcuUmVzdWx0IgASKwoM",
            "RXhlY3V0ZUJhdGNoEgYuUXVlcnkaDS5TdHJlYW1SZXN1bHQiACgBMAFCOVog",
            "Z2l0aHViLmNvbS9sbGtlbm5lZHkvbHNxbC9nb2xzcWyqAhRMdWtlS2VubmVk",
            "eS5MU1FMLk5ldGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::LukeKennedy.LSQL.Net.QueryReflection.Descriptor, global::LukeKennedy.LSQL.Net.ResultReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
