// source: query.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.Comparator', null, global);
goog.exportSymbol('proto.DomainJoins', null, global);
goog.exportSymbol('proto.GroupOperator', null, global);
goog.exportSymbol('proto.Ordering', null, global);
goog.exportSymbol('proto.Paging', null, global);
goog.exportSymbol('proto.Query', null, global);
goog.exportSymbol('proto.Query.DomainSpaceCase', null, global);
goog.exportSymbol('proto.WhereField', null, global);
goog.exportSymbol('proto.WhereField.ValueCase', null, global);
goog.exportSymbol('proto.WhereGroup', null, global);
goog.exportSymbol('proto.WhereGroupElement', null, global);
goog.exportSymbol('proto.WhereGroupElement.ElementCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Query = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.Query.oneofGroups_);
};
goog.inherits(proto.Query, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Query.displayName = 'proto.Query';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DomainJoins = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.DomainJoins, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.DomainJoins.displayName = 'proto.DomainJoins';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.WhereGroup = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.WhereGroup.repeatedFields_, null);
};
goog.inherits(proto.WhereGroup, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.WhereGroup.displayName = 'proto.WhereGroup';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.WhereGroupElement = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.WhereGroupElement.oneofGroups_);
};
goog.inherits(proto.WhereGroupElement, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.WhereGroupElement.displayName = 'proto.WhereGroupElement';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.WhereField = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.WhereField.oneofGroups_);
};
goog.inherits(proto.WhereField, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.WhereField.displayName = 'proto.WhereField';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Paging = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Paging, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Paging.displayName = 'proto.Paging';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Ordering = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Ordering, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Ordering.displayName = 'proto.Ordering';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.Query.oneofGroups_ = [[101]];

/**
 * @enum {number}
 */
proto.Query.DomainSpaceCase = {
  DOMAIN_SPACE_NOT_SET: 0,
  DOMAIN: 101
};

/**
 * @return {proto.Query.DomainSpaceCase}
 */
proto.Query.prototype.getDomainSpaceCase = function() {
  return /** @type {proto.Query.DomainSpaceCase} */(jspb.Message.computeOneofCase(this, proto.Query.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Query.prototype.toObject = function(opt_includeInstance) {
  return proto.Query.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Query} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Query.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    domain: jspb.Message.getFieldWithDefault(msg, 101, ""),
    paging: (f = msg.getPaging()) && proto.Paging.toObject(includeInstance, f),
    where: (f = msg.getWhere()) && proto.WhereGroup.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Query}
 */
proto.Query.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Query;
  return proto.Query.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Query} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Query}
 */
proto.Query.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 101:
      var value = /** @type {string} */ (reader.readString());
      msg.setDomain(value);
      break;
    case 2:
      var value = new proto.Paging;
      reader.readMessage(value,proto.Paging.deserializeBinaryFromReader);
      msg.setPaging(value);
      break;
    case 3:
      var value = new proto.WhereGroup;
      reader.readMessage(value,proto.WhereGroup.deserializeBinaryFromReader);
      msg.setWhere(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Query.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Query.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Query} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Query.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 101));
  if (f != null) {
    writer.writeString(
      101,
      f
    );
  }
  f = message.getPaging();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.Paging.serializeBinaryToWriter
    );
  }
  f = message.getWhere();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.WhereGroup.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.Query.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Query} returns this
 */
proto.Query.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string domain = 101;
 * @return {string}
 */
proto.Query.prototype.getDomain = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 101, ""));
};


/**
 * @param {string} value
 * @return {!proto.Query} returns this
 */
proto.Query.prototype.setDomain = function(value) {
  return jspb.Message.setOneofField(this, 101, proto.Query.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Query} returns this
 */
proto.Query.prototype.clearDomain = function() {
  return jspb.Message.setOneofField(this, 101, proto.Query.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Query.prototype.hasDomain = function() {
  return jspb.Message.getField(this, 101) != null;
};


/**
 * optional Paging paging = 2;
 * @return {?proto.Paging}
 */
proto.Query.prototype.getPaging = function() {
  return /** @type{?proto.Paging} */ (
    jspb.Message.getWrapperField(this, proto.Paging, 2));
};


/**
 * @param {?proto.Paging|undefined} value
 * @return {!proto.Query} returns this
*/
proto.Query.prototype.setPaging = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Query} returns this
 */
proto.Query.prototype.clearPaging = function() {
  return this.setPaging(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Query.prototype.hasPaging = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional WhereGroup where = 3;
 * @return {?proto.WhereGroup}
 */
proto.Query.prototype.getWhere = function() {
  return /** @type{?proto.WhereGroup} */ (
    jspb.Message.getWrapperField(this, proto.WhereGroup, 3));
};


/**
 * @param {?proto.WhereGroup|undefined} value
 * @return {!proto.Query} returns this
*/
proto.Query.prototype.setWhere = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Query} returns this
 */
proto.Query.prototype.clearWhere = function() {
  return this.setWhere(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Query.prototype.hasWhere = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DomainJoins.prototype.toObject = function(opt_includeInstance) {
  return proto.DomainJoins.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DomainJoins} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DomainJoins.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.DomainJoins}
 */
proto.DomainJoins.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.DomainJoins;
  return proto.DomainJoins.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.DomainJoins} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.DomainJoins}
 */
proto.DomainJoins.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.DomainJoins.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.DomainJoins.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.DomainJoins} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DomainJoins.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.WhereGroup.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.WhereGroup.prototype.toObject = function(opt_includeInstance) {
  return proto.WhereGroup.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.WhereGroup} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WhereGroup.toObject = function(includeInstance, msg) {
  var f, obj = {
    elementsList: jspb.Message.toObjectList(msg.getElementsList(),
    proto.WhereGroupElement.toObject, includeInstance),
    negateOperator: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    operator: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.WhereGroup}
 */
proto.WhereGroup.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.WhereGroup;
  return proto.WhereGroup.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.WhereGroup} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.WhereGroup}
 */
proto.WhereGroup.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.WhereGroupElement;
      reader.readMessage(value,proto.WhereGroupElement.deserializeBinaryFromReader);
      msg.addElements(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNegateOperator(value);
      break;
    case 3:
      var value = /** @type {!proto.GroupOperator} */ (reader.readEnum());
      msg.setOperator(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.WhereGroup.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.WhereGroup.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.WhereGroup} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WhereGroup.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getElementsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.WhereGroupElement.serializeBinaryToWriter
    );
  }
  f = message.getNegateOperator();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getOperator();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * repeated WhereGroupElement elements = 1;
 * @return {!Array<!proto.WhereGroupElement>}
 */
proto.WhereGroup.prototype.getElementsList = function() {
  return /** @type{!Array<!proto.WhereGroupElement>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.WhereGroupElement, 1));
};


/**
 * @param {!Array<!proto.WhereGroupElement>} value
 * @return {!proto.WhereGroup} returns this
*/
proto.WhereGroup.prototype.setElementsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.WhereGroupElement=} opt_value
 * @param {number=} opt_index
 * @return {!proto.WhereGroupElement}
 */
proto.WhereGroup.prototype.addElements = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.WhereGroupElement, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.WhereGroup} returns this
 */
proto.WhereGroup.prototype.clearElementsList = function() {
  return this.setElementsList([]);
};


/**
 * optional bool negate_operator = 2;
 * @return {boolean}
 */
proto.WhereGroup.prototype.getNegateOperator = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.WhereGroup} returns this
 */
proto.WhereGroup.prototype.setNegateOperator = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional GroupOperator operator = 3;
 * @return {!proto.GroupOperator}
 */
proto.WhereGroup.prototype.getOperator = function() {
  return /** @type {!proto.GroupOperator} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.GroupOperator} value
 * @return {!proto.WhereGroup} returns this
 */
proto.WhereGroup.prototype.setOperator = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.WhereGroupElement.oneofGroups_ = [[101,102]];

/**
 * @enum {number}
 */
proto.WhereGroupElement.ElementCase = {
  ELEMENT_NOT_SET: 0,
  FIELD: 101,
  GROUP: 102
};

/**
 * @return {proto.WhereGroupElement.ElementCase}
 */
proto.WhereGroupElement.prototype.getElementCase = function() {
  return /** @type {proto.WhereGroupElement.ElementCase} */(jspb.Message.computeOneofCase(this, proto.WhereGroupElement.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.WhereGroupElement.prototype.toObject = function(opt_includeInstance) {
  return proto.WhereGroupElement.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.WhereGroupElement} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WhereGroupElement.toObject = function(includeInstance, msg) {
  var f, obj = {
    field: (f = msg.getField()) && proto.WhereField.toObject(includeInstance, f),
    group: (f = msg.getGroup()) && proto.WhereGroup.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.WhereGroupElement}
 */
proto.WhereGroupElement.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.WhereGroupElement;
  return proto.WhereGroupElement.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.WhereGroupElement} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.WhereGroupElement}
 */
proto.WhereGroupElement.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 101:
      var value = new proto.WhereField;
      reader.readMessage(value,proto.WhereField.deserializeBinaryFromReader);
      msg.setField(value);
      break;
    case 102:
      var value = new proto.WhereGroup;
      reader.readMessage(value,proto.WhereGroup.deserializeBinaryFromReader);
      msg.setGroup(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.WhereGroupElement.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.WhereGroupElement.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.WhereGroupElement} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WhereGroupElement.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getField();
  if (f != null) {
    writer.writeMessage(
      101,
      f,
      proto.WhereField.serializeBinaryToWriter
    );
  }
  f = message.getGroup();
  if (f != null) {
    writer.writeMessage(
      102,
      f,
      proto.WhereGroup.serializeBinaryToWriter
    );
  }
};


/**
 * optional WhereField field = 101;
 * @return {?proto.WhereField}
 */
proto.WhereGroupElement.prototype.getField = function() {
  return /** @type{?proto.WhereField} */ (
    jspb.Message.getWrapperField(this, proto.WhereField, 101));
};


/**
 * @param {?proto.WhereField|undefined} value
 * @return {!proto.WhereGroupElement} returns this
*/
proto.WhereGroupElement.prototype.setField = function(value) {
  return jspb.Message.setOneofWrapperField(this, 101, proto.WhereGroupElement.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WhereGroupElement} returns this
 */
proto.WhereGroupElement.prototype.clearField = function() {
  return this.setField(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WhereGroupElement.prototype.hasField = function() {
  return jspb.Message.getField(this, 101) != null;
};


/**
 * optional WhereGroup group = 102;
 * @return {?proto.WhereGroup}
 */
proto.WhereGroupElement.prototype.getGroup = function() {
  return /** @type{?proto.WhereGroup} */ (
    jspb.Message.getWrapperField(this, proto.WhereGroup, 102));
};


/**
 * @param {?proto.WhereGroup|undefined} value
 * @return {!proto.WhereGroupElement} returns this
*/
proto.WhereGroupElement.prototype.setGroup = function(value) {
  return jspb.Message.setOneofWrapperField(this, 102, proto.WhereGroupElement.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WhereGroupElement} returns this
 */
proto.WhereGroupElement.prototype.clearGroup = function() {
  return this.setGroup(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WhereGroupElement.prototype.hasGroup = function() {
  return jspb.Message.getField(this, 102) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.WhereField.oneofGroups_ = [[101,102,103,104,105,106,107]];

/**
 * @enum {number}
 */
proto.WhereField.ValueCase = {
  VALUE_NOT_SET: 0,
  STRING_VALUE: 101,
  INT64_VALUE: 102,
  UINT64_VALUE: 103,
  DOUBLE_VALUE: 104,
  BOOL_VALUE: 105,
  BYTES_VALUE: 106,
  TIME_VALUE: 107
};

/**
 * @return {proto.WhereField.ValueCase}
 */
proto.WhereField.prototype.getValueCase = function() {
  return /** @type {proto.WhereField.ValueCase} */(jspb.Message.computeOneofCase(this, proto.WhereField.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.WhereField.prototype.toObject = function(opt_includeInstance) {
  return proto.WhereField.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.WhereField} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WhereField.toObject = function(includeInstance, msg) {
  var f, obj = {
    fieldName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    negateComparator: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    comparator: jspb.Message.getFieldWithDefault(msg, 3, 0),
    domainName: jspb.Message.getFieldWithDefault(msg, 4, ""),
    stringValue: jspb.Message.getFieldWithDefault(msg, 101, ""),
    int64Value: jspb.Message.getFieldWithDefault(msg, 102, 0),
    uint64Value: jspb.Message.getFieldWithDefault(msg, 103, 0),
    doubleValue: jspb.Message.getFloatingPointFieldWithDefault(msg, 104, 0.0),
    boolValue: jspb.Message.getBooleanFieldWithDefault(msg, 105, false),
    bytesValue: msg.getBytesValue_asB64(),
    timeValue: (f = msg.getTimeValue()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    ordering: (f = msg.getOrdering()) && proto.Ordering.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.WhereField}
 */
proto.WhereField.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.WhereField;
  return proto.WhereField.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.WhereField} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.WhereField}
 */
proto.WhereField.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFieldName(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNegateComparator(value);
      break;
    case 3:
      var value = /** @type {!proto.Comparator} */ (reader.readEnum());
      msg.setComparator(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDomainName(value);
      break;
    case 101:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringValue(value);
      break;
    case 102:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setInt64Value(value);
      break;
    case 103:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setUint64Value(value);
      break;
    case 104:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDoubleValue(value);
      break;
    case 105:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBoolValue(value);
      break;
    case 106:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBytesValue(value);
      break;
    case 107:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimeValue(value);
      break;
    case 5:
      var value = new proto.Ordering;
      reader.readMessage(value,proto.Ordering.deserializeBinaryFromReader);
      msg.setOrdering(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.WhereField.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.WhereField.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.WhereField} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WhereField.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFieldName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNegateComparator();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getComparator();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getDomainName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 101));
  if (f != null) {
    writer.writeString(
      101,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 102));
  if (f != null) {
    writer.writeInt64(
      102,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 103));
  if (f != null) {
    writer.writeUint64(
      103,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 104));
  if (f != null) {
    writer.writeDouble(
      104,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 105));
  if (f != null) {
    writer.writeBool(
      105,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 106));
  if (f != null) {
    writer.writeBytes(
      106,
      f
    );
  }
  f = message.getTimeValue();
  if (f != null) {
    writer.writeMessage(
      107,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getOrdering();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.Ordering.serializeBinaryToWriter
    );
  }
};


/**
 * optional string field_name = 1;
 * @return {string}
 */
proto.WhereField.prototype.getFieldName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.WhereField} returns this
 */
proto.WhereField.prototype.setFieldName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool negate_comparator = 2;
 * @return {boolean}
 */
proto.WhereField.prototype.getNegateComparator = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.WhereField} returns this
 */
proto.WhereField.prototype.setNegateComparator = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional Comparator comparator = 3;
 * @return {!proto.Comparator}
 */
proto.WhereField.prototype.getComparator = function() {
  return /** @type {!proto.Comparator} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.Comparator} value
 * @return {!proto.WhereField} returns this
 */
proto.WhereField.prototype.setComparator = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional string domain_name = 4;
 * @return {string}
 */
proto.WhereField.prototype.getDomainName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.WhereField} returns this
 */
proto.WhereField.prototype.setDomainName = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string string_value = 101;
 * @return {string}
 */
proto.WhereField.prototype.getStringValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 101, ""));
};


/**
 * @param {string} value
 * @return {!proto.WhereField} returns this
 */
proto.WhereField.prototype.setStringValue = function(value) {
  return jspb.Message.setOneofField(this, 101, proto.WhereField.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.WhereField} returns this
 */
proto.WhereField.prototype.clearStringValue = function() {
  return jspb.Message.setOneofField(this, 101, proto.WhereField.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WhereField.prototype.hasStringValue = function() {
  return jspb.Message.getField(this, 101) != null;
};


/**
 * optional int64 int64_value = 102;
 * @return {number}
 */
proto.WhereField.prototype.getInt64Value = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 102, 0));
};


/**
 * @param {number} value
 * @return {!proto.WhereField} returns this
 */
proto.WhereField.prototype.setInt64Value = function(value) {
  return jspb.Message.setOneofField(this, 102, proto.WhereField.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.WhereField} returns this
 */
proto.WhereField.prototype.clearInt64Value = function() {
  return jspb.Message.setOneofField(this, 102, proto.WhereField.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WhereField.prototype.hasInt64Value = function() {
  return jspb.Message.getField(this, 102) != null;
};


/**
 * optional uint64 uint64_value = 103;
 * @return {number}
 */
proto.WhereField.prototype.getUint64Value = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 103, 0));
};


/**
 * @param {number} value
 * @return {!proto.WhereField} returns this
 */
proto.WhereField.prototype.setUint64Value = function(value) {
  return jspb.Message.setOneofField(this, 103, proto.WhereField.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.WhereField} returns this
 */
proto.WhereField.prototype.clearUint64Value = function() {
  return jspb.Message.setOneofField(this, 103, proto.WhereField.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WhereField.prototype.hasUint64Value = function() {
  return jspb.Message.getField(this, 103) != null;
};


/**
 * optional double double_value = 104;
 * @return {number}
 */
proto.WhereField.prototype.getDoubleValue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 104, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.WhereField} returns this
 */
proto.WhereField.prototype.setDoubleValue = function(value) {
  return jspb.Message.setOneofField(this, 104, proto.WhereField.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.WhereField} returns this
 */
proto.WhereField.prototype.clearDoubleValue = function() {
  return jspb.Message.setOneofField(this, 104, proto.WhereField.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WhereField.prototype.hasDoubleValue = function() {
  return jspb.Message.getField(this, 104) != null;
};


/**
 * optional bool bool_value = 105;
 * @return {boolean}
 */
proto.WhereField.prototype.getBoolValue = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 105, false));
};


/**
 * @param {boolean} value
 * @return {!proto.WhereField} returns this
 */
proto.WhereField.prototype.setBoolValue = function(value) {
  return jspb.Message.setOneofField(this, 105, proto.WhereField.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.WhereField} returns this
 */
proto.WhereField.prototype.clearBoolValue = function() {
  return jspb.Message.setOneofField(this, 105, proto.WhereField.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WhereField.prototype.hasBoolValue = function() {
  return jspb.Message.getField(this, 105) != null;
};


/**
 * optional bytes bytes_value = 106;
 * @return {string}
 */
proto.WhereField.prototype.getBytesValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 106, ""));
};


/**
 * optional bytes bytes_value = 106;
 * This is a type-conversion wrapper around `getBytesValue()`
 * @return {string}
 */
proto.WhereField.prototype.getBytesValue_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBytesValue()));
};


/**
 * optional bytes bytes_value = 106;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBytesValue()`
 * @return {!Uint8Array}
 */
proto.WhereField.prototype.getBytesValue_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBytesValue()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.WhereField} returns this
 */
proto.WhereField.prototype.setBytesValue = function(value) {
  return jspb.Message.setOneofField(this, 106, proto.WhereField.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.WhereField} returns this
 */
proto.WhereField.prototype.clearBytesValue = function() {
  return jspb.Message.setOneofField(this, 106, proto.WhereField.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WhereField.prototype.hasBytesValue = function() {
  return jspb.Message.getField(this, 106) != null;
};


/**
 * optional google.protobuf.Timestamp time_value = 107;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.WhereField.prototype.getTimeValue = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 107));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.WhereField} returns this
*/
proto.WhereField.prototype.setTimeValue = function(value) {
  return jspb.Message.setOneofWrapperField(this, 107, proto.WhereField.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WhereField} returns this
 */
proto.WhereField.prototype.clearTimeValue = function() {
  return this.setTimeValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WhereField.prototype.hasTimeValue = function() {
  return jspb.Message.getField(this, 107) != null;
};


/**
 * optional Ordering ordering = 5;
 * @return {?proto.Ordering}
 */
proto.WhereField.prototype.getOrdering = function() {
  return /** @type{?proto.Ordering} */ (
    jspb.Message.getWrapperField(this, proto.Ordering, 5));
};


/**
 * @param {?proto.Ordering|undefined} value
 * @return {!proto.WhereField} returns this
*/
proto.WhereField.prototype.setOrdering = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.WhereField} returns this
 */
proto.WhereField.prototype.clearOrdering = function() {
  return this.setOrdering(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WhereField.prototype.hasOrdering = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Paging.prototype.toObject = function(opt_includeInstance) {
  return proto.Paging.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Paging} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Paging.toObject = function(includeInstance, msg) {
  var f, obj = {
    limit: jspb.Message.getFieldWithDefault(msg, 1, 0),
    offset: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Paging}
 */
proto.Paging.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Paging;
  return proto.Paging.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Paging} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Paging}
 */
proto.Paging.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLimit(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setOffset(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Paging.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Paging.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Paging} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Paging.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLimit();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getOffset();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
};


/**
 * optional uint64 limit = 1;
 * @return {number}
 */
proto.Paging.prototype.getLimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Paging} returns this
 */
proto.Paging.prototype.setLimit = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint64 offset = 2;
 * @return {number}
 */
proto.Paging.prototype.getOffset = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.Paging} returns this
 */
proto.Paging.prototype.setOffset = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Ordering.prototype.toObject = function(opt_includeInstance) {
  return proto.Ordering.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Ordering} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Ordering.toObject = function(includeInstance, msg) {
  var f, obj = {
    priority: jspb.Message.getFieldWithDefault(msg, 1, 0),
    descending: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Ordering}
 */
proto.Ordering.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Ordering;
  return proto.Ordering.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Ordering} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Ordering}
 */
proto.Ordering.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPriority(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDescending(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Ordering.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Ordering.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Ordering} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Ordering.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPriority();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getDescending();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional uint32 priority = 1;
 * @return {number}
 */
proto.Ordering.prototype.getPriority = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Ordering} returns this
 */
proto.Ordering.prototype.setPriority = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool descending = 2;
 * @return {boolean}
 */
proto.Ordering.prototype.getDescending = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Ordering} returns this
 */
proto.Ordering.prototype.setDescending = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.Comparator = {
  UNKNOWN_COMPARATOR: 0,
  EQUAL: 1,
  FUZZY_EQUAL: 2,
  GREATER_THAN: 3,
  LESS_THAN: 4,
  GREATER_THAN_OR_EQUAL: 5,
  LESS_THAN_OR_EQUAL: 6,
  IS_NULL: 7
};

/**
 * @enum {number}
 */
proto.GroupOperator = {
  UNKNOWN_GROUPOPERATOR: 0,
  AND: 1,
  OR: 2,
  XOR: 3
};

goog.object.extend(exports, proto);
