// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.1
// source: model.proto

package golsql

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Domain is a set of properties within a single logical surface,
// which may represent any number of database tables at the end of eventual query execution.
type Domain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name is the name of the domain. This should be globally unique, but no central authority is enforcing this.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Properties maps property names (must be unique within a domain) to type information.
	Properties map[string]*PropertyInformation `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Domain) Reset() {
	*x = Domain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

func (x *Domain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Domain) GetProperties() map[string]*PropertyInformation {
	if x != nil {
		return x.Properties
	}
	return nil
}

type PropertyInformation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// DisplayName is a decorative name to make properties clearer to users.
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// TypeAndLimits are the type and limits of the property.
	//
	// Types that are assignable to TypeAndLimits:
	//	*PropertyInformation_String_
	//	*PropertyInformation_Int64
	//	*PropertyInformation_Uint64
	//	*PropertyInformation_Double
	//	*PropertyInformation_Bool
	//	*PropertyInformation_Bytes
	//	*PropertyInformation_Timestamp
	TypeAndLimits isPropertyInformation_TypeAndLimits `protobuf_oneof:"type_and_limits"`
}

func (x *PropertyInformation) Reset() {
	*x = PropertyInformation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropertyInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyInformation) ProtoMessage() {}

func (x *PropertyInformation) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyInformation.ProtoReflect.Descriptor instead.
func (*PropertyInformation) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

func (x *PropertyInformation) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (m *PropertyInformation) GetTypeAndLimits() isPropertyInformation_TypeAndLimits {
	if m != nil {
		return m.TypeAndLimits
	}
	return nil
}

func (x *PropertyInformation) GetString_() *StringPropertyType {
	if x, ok := x.GetTypeAndLimits().(*PropertyInformation_String_); ok {
		return x.String_
	}
	return nil
}

func (x *PropertyInformation) GetInt64() *Int64PropertyType {
	if x, ok := x.GetTypeAndLimits().(*PropertyInformation_Int64); ok {
		return x.Int64
	}
	return nil
}

func (x *PropertyInformation) GetUint64() *Uint64PropertyType {
	if x, ok := x.GetTypeAndLimits().(*PropertyInformation_Uint64); ok {
		return x.Uint64
	}
	return nil
}

func (x *PropertyInformation) GetDouble() *DoublePropertyType {
	if x, ok := x.GetTypeAndLimits().(*PropertyInformation_Double); ok {
		return x.Double
	}
	return nil
}

func (x *PropertyInformation) GetBool() *BoolPropertyType {
	if x, ok := x.GetTypeAndLimits().(*PropertyInformation_Bool); ok {
		return x.Bool
	}
	return nil
}

func (x *PropertyInformation) GetBytes() *BytesPropertyType {
	if x, ok := x.GetTypeAndLimits().(*PropertyInformation_Bytes); ok {
		return x.Bytes
	}
	return nil
}

func (x *PropertyInformation) GetTimestamp() *TimestampPropertyType {
	if x, ok := x.GetTypeAndLimits().(*PropertyInformation_Timestamp); ok {
		return x.Timestamp
	}
	return nil
}

type isPropertyInformation_TypeAndLimits interface {
	isPropertyInformation_TypeAndLimits()
}

type PropertyInformation_String_ struct {
	String_ *StringPropertyType `protobuf:"bytes,101,opt,name=string,proto3,oneof"`
}

type PropertyInformation_Int64 struct {
	Int64 *Int64PropertyType `protobuf:"bytes,102,opt,name=int64,proto3,oneof"`
}

type PropertyInformation_Uint64 struct {
	Uint64 *Uint64PropertyType `protobuf:"bytes,103,opt,name=uint64,proto3,oneof"`
}

type PropertyInformation_Double struct {
	Double *DoublePropertyType `protobuf:"bytes,104,opt,name=double,proto3,oneof"`
}

type PropertyInformation_Bool struct {
	Bool *BoolPropertyType `protobuf:"bytes,105,opt,name=bool,proto3,oneof"`
}

type PropertyInformation_Bytes struct {
	Bytes *BytesPropertyType `protobuf:"bytes,106,opt,name=bytes,proto3,oneof"`
}

type PropertyInformation_Timestamp struct {
	Timestamp *TimestampPropertyType `protobuf:"bytes,107,opt,name=timestamp,proto3,oneof"`
}

func (*PropertyInformation_String_) isPropertyInformation_TypeAndLimits() {}

func (*PropertyInformation_Int64) isPropertyInformation_TypeAndLimits() {}

func (*PropertyInformation_Uint64) isPropertyInformation_TypeAndLimits() {}

func (*PropertyInformation_Double) isPropertyInformation_TypeAndLimits() {}

func (*PropertyInformation_Bool) isPropertyInformation_TypeAndLimits() {}

func (*PropertyInformation_Bytes) isPropertyInformation_TypeAndLimits() {}

func (*PropertyInformation_Timestamp) isPropertyInformation_TypeAndLimits() {}

type StringPropertyType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// LengthMinimum sets a minimum length, 0 = no limit
	LengthMinimum uint32 `protobuf:"varint,1,opt,name=length_minimum,json=lengthMinimum,proto3" json:"length_minimum,omitempty"`
	// LengthMaximum sets a maximum length, 0 = no limit
	LengthMaximum uint32 `protobuf:"varint,2,opt,name=length_maximum,json=lengthMaximum,proto3" json:"length_maximum,omitempty"`
	// CharacterSet sets a limit on the characters expected to exist in the property, and therefore can be used to validate Select input.
	CharacterSet string `protobuf:"bytes,3,opt,name=character_set,json=characterSet,proto3" json:"character_set,omitempty"`
	// QueryValidationRegex is a regular expresession which overrides character set and validates query input - it does not imply that real data values must obey this rule, only Select inputs.
	QueryValidationRegex string `protobuf:"bytes,4,opt,name=query_validation_regex,json=queryValidationRegex,proto3" json:"query_validation_regex,omitempty"`
}

func (x *StringPropertyType) Reset() {
	*x = StringPropertyType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringPropertyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringPropertyType) ProtoMessage() {}

func (x *StringPropertyType) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringPropertyType.ProtoReflect.Descriptor instead.
func (*StringPropertyType) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{2}
}

func (x *StringPropertyType) GetLengthMinimum() uint32 {
	if x != nil {
		return x.LengthMinimum
	}
	return 0
}

func (x *StringPropertyType) GetLengthMaximum() uint32 {
	if x != nil {
		return x.LengthMaximum
	}
	return 0
}

func (x *StringPropertyType) GetCharacterSet() string {
	if x != nil {
		return x.CharacterSet
	}
	return ""
}

func (x *StringPropertyType) GetQueryValidationRegex() string {
	if x != nil {
		return x.QueryValidationRegex
	}
	return ""
}

type Int64PropertyType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// MinimumValue sets a minimum limit of the value, 0 = no limit
	MinimumValue int64 `protobuf:"varint,1,opt,name=minimum_value,json=minimumValue,proto3" json:"minimum_value,omitempty"`
	// MaximumValue sets a maximum limit of the value, 0 = no limit
	MaximumValue int64 `protobuf:"varint,2,opt,name=maximum_value,json=maximumValue,proto3" json:"maximum_value,omitempty"`
}

func (x *Int64PropertyType) Reset() {
	*x = Int64PropertyType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int64PropertyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64PropertyType) ProtoMessage() {}

func (x *Int64PropertyType) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64PropertyType.ProtoReflect.Descriptor instead.
func (*Int64PropertyType) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{3}
}

func (x *Int64PropertyType) GetMinimumValue() int64 {
	if x != nil {
		return x.MinimumValue
	}
	return 0
}

func (x *Int64PropertyType) GetMaximumValue() int64 {
	if x != nil {
		return x.MaximumValue
	}
	return 0
}

type Uint64PropertyType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// MinimumValue sets a minimum limit of the value, 0 = no limit
	MinimumValue uint64 `protobuf:"varint,1,opt,name=minimum_value,json=minimumValue,proto3" json:"minimum_value,omitempty"`
	// MaximumValue sets a maximum limit of the value, 0 = no limit
	MaximumValue uint64 `protobuf:"varint,2,opt,name=maximum_value,json=maximumValue,proto3" json:"maximum_value,omitempty"`
}

func (x *Uint64PropertyType) Reset() {
	*x = Uint64PropertyType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uint64PropertyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint64PropertyType) ProtoMessage() {}

func (x *Uint64PropertyType) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint64PropertyType.ProtoReflect.Descriptor instead.
func (*Uint64PropertyType) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{4}
}

func (x *Uint64PropertyType) GetMinimumValue() uint64 {
	if x != nil {
		return x.MinimumValue
	}
	return 0
}

func (x *Uint64PropertyType) GetMaximumValue() uint64 {
	if x != nil {
		return x.MaximumValue
	}
	return 0
}

type DoublePropertyType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// MinimumValue sets a minimum limit of the value, 0 = no limit
	MinimumValue float64 `protobuf:"fixed64,1,opt,name=minimum_value,json=minimumValue,proto3" json:"minimum_value,omitempty"`
	// MaximumValue sets a maximum limit of the value, 0 = no limit
	MaximumValue float64 `protobuf:"fixed64,2,opt,name=maximum_value,json=maximumValue,proto3" json:"maximum_value,omitempty"`
}

func (x *DoublePropertyType) Reset() {
	*x = DoublePropertyType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoublePropertyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoublePropertyType) ProtoMessage() {}

func (x *DoublePropertyType) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoublePropertyType.ProtoReflect.Descriptor instead.
func (*DoublePropertyType) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{5}
}

func (x *DoublePropertyType) GetMinimumValue() float64 {
	if x != nil {
		return x.MinimumValue
	}
	return 0
}

func (x *DoublePropertyType) GetMaximumValue() float64 {
	if x != nil {
		return x.MaximumValue
	}
	return 0
}

type BoolPropertyType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BoolPropertyType) Reset() {
	*x = BoolPropertyType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolPropertyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolPropertyType) ProtoMessage() {}

func (x *BoolPropertyType) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolPropertyType.ProtoReflect.Descriptor instead.
func (*BoolPropertyType) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{6}
}

type BytesPropertyType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// LengthMinimum sets a minimum length, 0 = no limit
	LengthMinimum uint32 `protobuf:"varint,1,opt,name=length_minimum,json=lengthMinimum,proto3" json:"length_minimum,omitempty"`
	// LengthMaximum sets a maximum length, 0 = no limit
	LengthMaximum uint32 `protobuf:"varint,2,opt,name=length_maximum,json=lengthMaximum,proto3" json:"length_maximum,omitempty"`
}

func (x *BytesPropertyType) Reset() {
	*x = BytesPropertyType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BytesPropertyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesPropertyType) ProtoMessage() {}

func (x *BytesPropertyType) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesPropertyType.ProtoReflect.Descriptor instead.
func (*BytesPropertyType) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{7}
}

func (x *BytesPropertyType) GetLengthMinimum() uint32 {
	if x != nil {
		return x.LengthMinimum
	}
	return 0
}

func (x *BytesPropertyType) GetLengthMaximum() uint32 {
	if x != nil {
		return x.LengthMaximum
	}
	return 0
}

type TimestampPropertyType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// MinimumValue sets a minimum limit of the value, 0 = no limit
	MinimumValue *timestamp.Timestamp `protobuf:"bytes,1,opt,name=minimum_value,json=minimumValue,proto3" json:"minimum_value,omitempty"`
	// MaximumValue sets a maximum limit of the value, 0 = no limit
	MaximumValue *timestamp.Timestamp `protobuf:"bytes,2,opt,name=maximum_value,json=maximumValue,proto3" json:"maximum_value,omitempty"`
}

func (x *TimestampPropertyType) Reset() {
	*x = TimestampPropertyType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimestampPropertyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimestampPropertyType) ProtoMessage() {}

func (x *TimestampPropertyType) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimestampPropertyType.ProtoReflect.Descriptor instead.
func (*TimestampPropertyType) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{8}
}

func (x *TimestampPropertyType) GetMinimumValue() *timestamp.Timestamp {
	if x != nil {
		return x.MinimumValue
	}
	return nil
}

func (x *TimestampPropertyType) GetMaximumValue() *timestamp.Timestamp {
	if x != nil {
		return x.MaximumValue
	}
	return nil
}

var File_model_proto protoreflect.FileDescriptor

var file_model_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaa,
	0x01, 0x0a, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x37, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x53, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x50, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x91, 0x03, 0x0a, 0x13,
	0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x06, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x2a, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x66,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x36,
	0x34, 0x12, 0x2d, 0x0a, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x67, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x06, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34,
	0x12, 0x2d, 0x0a, 0x06, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x18, 0x68, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x06, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12,
	0x27, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x69, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x42, 0x6f, 0x6f, 0x6c, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x48, 0x00, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12, 0x2a, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x6a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x05, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x6b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x48,
	0x00, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x11, 0x0a, 0x0f,
	0x74, 0x79, 0x70, 0x65, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x22,
	0xbd, 0x01, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x5f, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x12, 0x25, 0x0a,
	0x0e, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x5f, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x4d, 0x61, 0x78,
	0x69, 0x6d, 0x75, 0x6d, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53, 0x65, 0x74, 0x12, 0x34, 0x0a, 0x16, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65,
	0x67, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x67, 0x65, 0x78, 0x22,
	0x5d, 0x0a, 0x11, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6d, 0x69, 0x6e,
	0x69, 0x6d, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x78,
	0x69, 0x6d, 0x75, 0x6d, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x5e,
	0x0a, 0x12, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x6d, 0x69, 0x6e,
	0x69, 0x6d, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x78,
	0x69, 0x6d, 0x75, 0x6d, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0c, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x5e,
	0x0a, 0x12, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x6d, 0x69, 0x6e,
	0x69, 0x6d, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x78,
	0x69, 0x6d, 0x75, 0x6d, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0c, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x12,
	0x0a, 0x10, 0x42, 0x6f, 0x6f, 0x6c, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x61, 0x0a, 0x11, 0x42, 0x79, 0x74, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x5f, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0d, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x12, 0x25,
	0x0a, 0x0e, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x5f, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x4d, 0x61,
	0x78, 0x69, 0x6d, 0x75, 0x6d, 0x22, 0x99, 0x01, 0x0a, 0x15, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x3f, 0x0a, 0x0d, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0c, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x3f, 0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0c, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x42, 0x39, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6c, 0x6c, 0x6b, 0x65, 0x6e, 0x6e, 0x65, 0x64, 0x79, 0x2f, 0x6c, 0x73, 0x71, 0x6c, 0x2f, 0x67,
	0x6f, 0x6c, 0x73, 0x71, 0x6c, 0xaa, 0x02, 0x14, 0x4c, 0x75, 0x6b, 0x65, 0x4b, 0x65, 0x6e, 0x6e,
	0x65, 0x64, 0x79, 0x2e, 0x4c, 0x53, 0x51, 0x4c, 0x2e, 0x4e, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_proto_rawDescOnce sync.Once
	file_model_proto_rawDescData = file_model_proto_rawDesc
)

func file_model_proto_rawDescGZIP() []byte {
	file_model_proto_rawDescOnce.Do(func() {
		file_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_proto_rawDescData)
	})
	return file_model_proto_rawDescData
}

var file_model_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_model_proto_goTypes = []interface{}{
	(*Domain)(nil),                // 0: Domain
	(*PropertyInformation)(nil),   // 1: PropertyInformation
	(*StringPropertyType)(nil),    // 2: StringPropertyType
	(*Int64PropertyType)(nil),     // 3: Int64PropertyType
	(*Uint64PropertyType)(nil),    // 4: Uint64PropertyType
	(*DoublePropertyType)(nil),    // 5: DoublePropertyType
	(*BoolPropertyType)(nil),      // 6: BoolPropertyType
	(*BytesPropertyType)(nil),     // 7: BytesPropertyType
	(*TimestampPropertyType)(nil), // 8: TimestampPropertyType
	nil,                           // 9: Domain.PropertiesEntry
	(*timestamp.Timestamp)(nil),   // 10: google.protobuf.Timestamp
}
var file_model_proto_depIdxs = []int32{
	9,  // 0: Domain.properties:type_name -> Domain.PropertiesEntry
	2,  // 1: PropertyInformation.string:type_name -> StringPropertyType
	3,  // 2: PropertyInformation.int64:type_name -> Int64PropertyType
	4,  // 3: PropertyInformation.uint64:type_name -> Uint64PropertyType
	5,  // 4: PropertyInformation.double:type_name -> DoublePropertyType
	6,  // 5: PropertyInformation.bool:type_name -> BoolPropertyType
	7,  // 6: PropertyInformation.bytes:type_name -> BytesPropertyType
	8,  // 7: PropertyInformation.timestamp:type_name -> TimestampPropertyType
	10, // 8: TimestampPropertyType.minimum_value:type_name -> google.protobuf.Timestamp
	10, // 9: TimestampPropertyType.maximum_value:type_name -> google.protobuf.Timestamp
	1,  // 10: Domain.PropertiesEntry.value:type_name -> PropertyInformation
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_model_proto_init() }
func file_model_proto_init() {
	if File_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Domain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PropertyInformation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringPropertyType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int64PropertyType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Uint64PropertyType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoublePropertyType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoolPropertyType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BytesPropertyType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimestampPropertyType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_model_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*PropertyInformation_String_)(nil),
		(*PropertyInformation_Int64)(nil),
		(*PropertyInformation_Uint64)(nil),
		(*PropertyInformation_Double)(nil),
		(*PropertyInformation_Bool)(nil),
		(*PropertyInformation_Bytes)(nil),
		(*PropertyInformation_Timestamp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_proto_goTypes,
		DependencyIndexes: file_model_proto_depIdxs,
		MessageInfos:      file_model_proto_msgTypes,
	}.Build()
	File_model_proto = out.File
	file_model_proto_rawDesc = nil
	file_model_proto_goTypes = nil
	file_model_proto_depIdxs = nil
}
